//
//  Keys.swift
//  Randomquiz
//
//  Created by Kushal Ashok on 12/19/17.
//  Copyright © 2017 Essex Lake Group. All rights reserved.
//

import Cocoa

var keyDictionary = Dictionary<Int,String>()

func prepareKeys() {
    keyDictionary[1] = "B"
    keyDictionary[2] = "B"
    keyDictionary[3] = "D"
    keyDictionary[4] = "B"
    keyDictionary[5] = "E"
    keyDictionary[6] = "C"
    keyDictionary[7] = "C"
    keyDictionary[8] = "E"
    keyDictionary[9] = "C"
    keyDictionary[10] = "G"
    keyDictionary[11] = "E"
    keyDictionary[12] = "B"
    keyDictionary[13] = "C"
    keyDictionary[14] = "C"
    keyDictionary[15] = "B"
    keyDictionary[16] = "C"
    keyDictionary[17] = "C"
    keyDictionary[18] = "F"
    keyDictionary[19] = "B"
    keyDictionary[20] = "B"
    keyDictionary[21] = "A"
    keyDictionary[22] = "A"
    keyDictionary[23] = "D"
    keyDictionary[24] = "E"
    keyDictionary[25] = "E"
    keyDictionary[26] = "C"
    keyDictionary[27] = "D"
    keyDictionary[28] = "F"
    keyDictionary[29] = "A"
    keyDictionary[30] = "B"
    keyDictionary[31] = "F"
    keyDictionary[32] = "A"
    keyDictionary[33] = "A"
    keyDictionary[34] = "G"
    keyDictionary[35] = "F"
    keyDictionary[36] = "B"
    keyDictionary[37] = "E"
    keyDictionary[38] = "D"
    keyDictionary[39] = "B"
    keyDictionary[40] = "D"
    keyDictionary[41] = "C"
    keyDictionary[42] = "A"
    keyDictionary[43] = "B"
    keyDictionary[44] = "C"
    keyDictionary[45] = "C"
    keyDictionary[46] = "E"
    keyDictionary[47] = "E"
    keyDictionary[48] = "G"
    keyDictionary[49] = "A"
    keyDictionary[50] = "C"
    keyDictionary[51] = "G"
    keyDictionary[52] = "C"
    keyDictionary[53] = "C"
    keyDictionary[54] = "C"
    keyDictionary[55] = "B"
    keyDictionary[56] = "F"
    keyDictionary[57] = "E"
    keyDictionary[58] = "C"
    keyDictionary[59] = "C"
    keyDictionary[60] = "A"
    keyDictionary[61] = "F"
    keyDictionary[62] = "E"
    keyDictionary[63] = "A"
    keyDictionary[64] = "F"
    keyDictionary[65] = "B"
    keyDictionary[66] = "G"
    keyDictionary[67] = "B"
    keyDictionary[68] = "E"
    keyDictionary[69] = "A"
    keyDictionary[70] = "B"
    keyDictionary[71] = "B"
    keyDictionary[72] = "E"
    keyDictionary[73] = "D"
    keyDictionary[74] = "C"
    keyDictionary[75] = "A"
    keyDictionary[76] = "A"
    keyDictionary[77] = "B"
    keyDictionary[78] = "F"
    keyDictionary[79] = "D"
    keyDictionary[80] = "A"
}


